name: Continuous Integration
on: [push]                      # Will make the workflow run every time you push to any branch

jobs:
  build:
    name: Build and test
    runs-on: ubuntu-latest      # Sets the build environment a machine with the latest Ubuntu installed
    steps:
    - uses: actions/checkout@v2 # Adds a step to checkout the repository code
    
    - name: DotNet Build
      run: dotnet build

    - name: npm build
      run: |
        cd DotnetTemplate.Web
        npm install
        npm run build
    
    - name: DotNet Test
      run: dotnet test

    - name: npm test
      run: |
        cd DotnetTemplate.Web
        npm t
    
    - name: npm linting
      run: npm run lint